// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBWRvtml-JueMU8f3Dw7NJ58sxSoHyc2M',
    appId: '1:558851719299:web:166b8962977da809d25bb6',
    messagingSenderId: '558851719299',
    projectId: 'flelobna',
    authDomain: 'flelobna.firebaseapp.com',
    storageBucket: 'flelobna.appspot.com',
    measurementId: 'G-ZSKTTEQHSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsXkj3DXRksdydPt4WoNHT_5RtpVTHAk',
    appId: '1:558851719299:android:b5f3b7128518ca48d25bb6',
    messagingSenderId: '558851719299',
    projectId: 'flelobna',
    storageBucket: 'flelobna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0OVcnFAOGMDDuUvX_HR37zbpjuVWuiXg',
    appId: '1:558851719299:ios:42475e606ede452dd25bb6',
    messagingSenderId: '558851719299',
    projectId: 'flelobna',
    storageBucket: 'flelobna.appspot.com',
    iosBundleId: 'com.alphadev.flelobna.flelobna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0OVcnFAOGMDDuUvX_HR37zbpjuVWuiXg',
    appId: '1:558851719299:ios:52551a9b352de3f6d25bb6',
    messagingSenderId: '558851719299',
    projectId: 'flelobna',
    storageBucket: 'flelobna.appspot.com',
    iosBundleId: 'com.alphadev.flelobna.flelobna.RunnerTests',
  );
}
